language: php

dist: trusty

php:
  - '7.1'
  - '7.0'
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:
  - composer install -o

script:
  - composer test