language: php

dist: trusty

php:
  - '7.1'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer install -o

script:
  - composer test