language: php

dist: trusty
sudo: required

git:
    depth: 1

php:
  - '7.1'
  - '7.0'
  - hhvm-nightly
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: nightly

#services:
#    - redis-server

before_install:
   - |
      # HHVM INI configuration
      if [[ $PHP = hhvm* ]]; then
          INI=/etc/hhvm/php.ini
          echo hhvm.jit = 0 >> $INI
          echo hhvm.php7.all = 1 >> $INI
          echo hhvm.php7.scalar_types = 0 >> $INI
      fi

install:
  - travis_retry composer install -o --no-interaction --ignore-platform-reqs

script:
  - composer test

after_script:
  - if [ -f php.log ] ; then cat php.log ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2c412be46f958d54dc6e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always