language: php

dist: trusty
group: edge
sudo: required

git:
    depth: 1

php:
  - '7.1'
  - '7.0'
  - nightly
  - hhvm

#services:
#    - redis-server

matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm
      - php: nightly

before_install:
   - |
      # HHVM INI configuration
      if [[ $PHP = hhvm* ]]; then
          INI=/etc/hhvm/php.ini
          echo "hhvm.jit = false" >> $INI
          echo "hhvm.php7.all = true" >> $INI
          echo "hhvm.php7.scalar_types = true" >> $INI
      fi

install:
  - travis_retry composer install -o --no-interaction --ignore-platform-reqs
  - composer dumpautoload -o

script:
  - composer test

after_script:
  - if [ -f php.log ] ; then cat php.log ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2c412be46f958d54dc6e
    on_success: always
    on_failure: always
    on_start: always