language: php

dist: trusty

php:
  - '7.1'
  - '7.0'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - travis_retry composer install -o --no-interaction

script:
  - composer test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2c412be46f958d54dc6e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always